# Production compose file - uses pre-built images
version: '3.8'

services:
  api:
    image: ghcr.io/nicholasmparker/imageupscaler-api:latest
    environment:
      - REDIS_HOST=truenas.chickenmilkbomb.com
      - REDIS_PORT=30036
      - REDIS_PASSWORD=1d3pdn
      - ESRGAN_HOST=esrgan
      - ESRGAN_PORT=8001
    networks:
      - upscaler-network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - esrgan
    restart: unless-stopped

  esrgan:
    image: ghcr.io/nicholasmparker/imageupscaler-esrgan:latest
    environment:
      - USE_GPU=false
      - MODEL_PATH=/app/models/RealESRGAN_x4plus.pth
    networks:
      - upscaler-network
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  upscaler-network:
    driver: bridge
