# Development compose file - uses local builds and volumes
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=truenas.chickenmilkbomb.com
      - REDIS_PORT=30036
      - REDIS_PASSWORD=1d3pdn
      - ESRGAN_HOST=esrgan
      - ESRGAN_PORT=8001
    networks:
      - upscaler-network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - esrgan

  esrgan:
    build:
      context: .
      dockerfile: Dockerfile.esrgan
    volumes:
      - ./models:/app/models
    environment:
      - USE_GPU=false
      - MODEL_PATH=/app/models/RealESRGAN_x4plus.pth
    networks:
      - upscaler-network
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
    command: python -m pytest tests/e2e/test_upscale.py -v
    environment:
      - API_HOST=api
      - API_PORT=8000
    networks:
      - upscaler-network
    depends_on:
      - api
      - esrgan

  test-webhook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - WEBHOOK_HOST=test-webhook
      - WEBHOOK_PORT=9090
      - API_HOST=api
      - API_PORT=8000
    command: python tests/e2e/test_webhook.py tests/e2e/images/bird.jpg
    depends_on:
      api:
        condition: service_healthy
      esrgan:
        condition: service_healthy
    networks:
      - upscaler-network
    ports:
      - "9090:9090"

networks:
  upscaler-network:
    driver: bridge
