# Build compose file - for building and pushing images
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/nicholasmparker/imageupscaler-api:latest

  esrgan:
    build:
      context: .
      dockerfile: Dockerfile.esrgan
    image: ghcr.io/nicholasmparker/imageupscaler-esrgan:latest
