version: '3.8'

services:
  init:
    image: curlimages/curl:latest
    command: |
      sh -c '
      mkdir -p /models &&
      if [ ! -f "/models/RealESRGAN_x4plus.pth" ]; then
        echo "Downloading RealESRGAN model..." &&
        curl -L https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth -o /models/RealESRGAN_x4plus.pth;
      else
        echo "Model already exists";
      fi'
    volumes:
      - esrgan_models:/models

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASSWORD=
      - ESRGAN_HOST=esrgan
      - ESRGAN_PORT=8001
    networks:
      - upscaler-network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - redis
      - esrgan
    restart: unless-stopped

  esrgan:
    build:
      context: .
      dockerfile: Dockerfile.esrgan
    environment:
      - USE_GPU=false
      - MODEL_PATH=/models/RealESRGAN_x4plus.pth
    volumes:
      - esrgan_models:/models
    networks:
      - upscaler-network
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    networks:
      - upscaler-network
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  esrgan_models:
  redis_data:

networks:
  upscaler-network:
    driver: bridge
