services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=truenas.chickenmilkbomb.com
      - REDIS_PORT=30036
    networks:
      - upscaler-network
    depends_on:
      - esrgan
    ports:
      - "8000:8000"

  esrgan:
    build:
      context: .
      dockerfile: Dockerfile.esrgan
    volumes:
      - esrgan_models:/app/models
    environment:
      - USE_GPU=${USE_GPU:-false}
    networks:
      - upscaler-network
    ports:
      - "8001:8001"

networks:
  upscaler-network:
    driver: bridge

volumes:
  esrgan_models:
    driver: local
