services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ESRGAN_HOST=esrgan
      - ESRGAN_PORT=8001
    networks:
      - upscaler-network
    depends_on:
      - esrgan
    ports:
      - "8000:8000"

  esrgan:
    build:
      context: .
      dockerfile: Dockerfile.esrgan
    volumes:
      - ./models:/app/models
    environment:
      - USE_GPU=${USE_GPU:-false}
    networks:
      - upscaler-network
    ports:
      - "8001:8001"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests:/app/tests
    command: python -m pytest tests/e2e/test_upscale.py -v
    environment:
      - API_HOST=api
      - API_PORT=8000
    networks:
      - upscaler-network
    depends_on:
      - api
      - esrgan

networks:
  upscaler-network:
    driver: bridge

volumes:
  esrgan_models:
    driver: local
