name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Aggressive cleanup before build
      - name: Cleanup
        run: |
          # Remove unnecessary large packages
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/swift

          # Clean Docker system
          docker system prune -af

          # Clean package manager cache
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

          # Remove pip cache
          pip cache purge

          # Show disk space before build
          df -h

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # Cache ESRGAN model
      - name: Cache ESRGAN model
        id: cache-model
        uses: actions/cache@v3
        with:
          path: models/RealESRGAN_x4plus.pth
          key: esrgan-model-v1

      # Download model if not cached
      - name: Download ESRGAN model if needed
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: |
          mkdir -p models
          wget -O models/RealESRGAN_x4plus.pth https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      # Run linting and formatting checks
      - name: Run linting checks
        run: |
          black . --check
          ruff check .

      # Build Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Copy model into Docker context
      - name: Prepare Docker context
        run: |
          mkdir -p .docker-context/models
          cp models/RealESRGAN_x4plus.pth .docker-context/models/
          cp -r esrgan_service .docker-context/
          cp Dockerfile.esrgan .docker-context/
          cp -r requirements .docker-context/

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .docker-context
          push: false
          load: true
          tags: imageupscaler:latest
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
          build-args: |
            BUILDKIT_STEP_LOG_MAX_SIZE=10485760

      # Run tests
      - name: Run tests
        run: pytest

      # Final cleanup
      - name: Post-build cleanup
        if: always()
        run: |
          docker system prune -af
          sudo rm -rf /tmp/*
          df -h
