name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push API image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/imageupscaler-api:latest
          ghcr.io/${{ github.repository_owner }}/imageupscaler-api:${{ github.sha }}
        
    - name: Build and push ESRGAN image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.esrgan
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/imageupscaler-esrgan:latest
          ghcr.io/${{ github.repository_owner }}/imageupscaler-esrgan:${{ github.sha }}
