name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'esrgan_service/**'
      - 'requirements/**'
      - 'Dockerfile'
      - 'Dockerfile.esrgan'
      - 'docker-compose*.yml'
  workflow_dispatch:  # Allow manual triggers

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  API_IMAGE_NAME: imageupscaler-api
  ESRGAN_IMAGE_NAME: imageupscaler-esrgan

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push ESRGAN image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.esrgan
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.ESRGAN_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
